/**
 * Manual source metadata — the single source of truth for source classification.
 * Do not auto-classify. Manual is correct for v1.
 */

export type SourceTier = 1 | 2 | 3 | 4;

export type SourceType =
  | "public_service"
  | "national_daily"
  | "regional_daily"
  | "local_paper"
  | "wire"
  | "trade_specialist"
  | "investigative"
  | "institutional";

export interface SourceMeta {
  slug: string;
  name: string;
  tier: SourceTier;
  type: SourceType;
  country: string;
  region: string;
  language: string;
  isMajor: boolean;
  isPublicService: boolean;
  municipality?: string;
  ownershipGroup?: string;
  feedUrl?: string;
  homepageUrl?: string;
}

// ─── Alias map for entity normalization ─────────────────────────────────────
export const ENTITY_ALIASES: Record<string, string> = {
  // Swedish political figures
  "ulf kristersson": "ulf kristersson",
  "kristersson": "ulf kristersson",
  "magdalena andersson": "magdalena andersson",
  "andersson": "magdalena andersson",
  "ebba busch": "ebba busch",
  "busch": "ebba busch",
  "jimmie åkesson": "jimmie åkesson",
  "åkesson": "jimmie åkesson",
  // Swedish institutions
  "svt": "svt nyheter",
  "svt nyheter": "svt nyheter",
  "sr": "sr ekot",
  "sr ekot": "sr ekot",
  "sveriges radio": "sr ekot",
  "sveriges television": "svt nyheter",
  "dagens nyheter": "dn",
  "dn": "dn",
  "svenska dagbladet": "svd",
  "svd": "svd",
  "göteborgs-posten": "gp",
  "gp": "gp",
  // Swedish government
  "riksdagen": "riksdagen",
  "regeringen": "regeringen",
  "regeringskansliet": "regeringen",
  // Wire services
  "tt": "tt",
  "tidningarnas telegrambyrå": "tt",
  "ap": "associated press",
  "associated press": "associated press",
  "reuters": "reuters",
  "afp": "afp",
  "agence france-presse": "afp",
};

// ─── Swedish sources ────────────────────────────────────────────────────────

const SWEDISH_SOURCES: SourceMeta[] = [
  // Tier 1 — major national
  {
    slug: "svt-nyheter",
    name: "SVT Nyheter",
    tier: 1,
    type: "public_service",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: true,
    feedUrl: "https://www.svt.se/nyheter/rss.xml",
    homepageUrl: "https://www.svt.se/nyheter",
  },
  {
    slug: "sr-ekot",
    name: "SR Ekot",
    tier: 1,
    type: "public_service",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: true,
    feedUrl: "https://api.sr.se/api/rss/program/83",
    homepageUrl: "https://sverigesradio.se/ekot",
  },
  {
    slug: "dn",
    name: "DN",
    tier: 1,
    type: "national_daily",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: false,
    ownershipGroup: "Bonnier",
    feedUrl: "https://www.dn.se/rss/",
    homepageUrl: "https://www.dn.se",
  },
  {
    slug: "svd",
    name: "SvD",
    tier: 1,
    type: "national_daily",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: false,
    ownershipGroup: "Schibsted",
    feedUrl: "https://www.svd.se/feed/articles.rss",
    homepageUrl: "https://www.svd.se",
  },
  {
    slug: "expressen",
    name: "Expressen",
    tier: 1,
    type: "national_daily",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: false,
    ownershipGroup: "Bonnier",
    feedUrl: "https://feeds.expressen.se/nyheter",
    homepageUrl: "https://www.expressen.se",
  },
  {
    slug: "aftonbladet",
    name: "Aftonbladet",
    tier: 1,
    type: "national_daily",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: true,
    isPublicService: false,
    ownershipGroup: "Schibsted",
    feedUrl: "https://rss.aftonbladet.se/rss2/small/pages/sections/senastenytt/",
    homepageUrl: "https://www.aftonbladet.se",
  },
  // Tier 2 — regional dailies and quality trade
  {
    slug: "gp",
    name: "GP",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Västra Götaland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    ownershipGroup: "Stampen",
    municipality: "Göteborg",
    feedUrl: "https://www.gp.se/rss",
    homepageUrl: "https://www.gp.se",
  },
  {
    slug: "sydsvenskan",
    name: "Sydsvenskan",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Skåne",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    ownershipGroup: "Bonnier",
    municipality: "Malmö",
    feedUrl: "https://www.sydsvenskan.se/rss.xml",
    homepageUrl: "https://www.sydsvenskan.se",
  },
  {
    slug: "helsingborgs-dagblad",
    name: "Helsingborgs Dagblad",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Skåne",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Helsingborg",
    homepageUrl: "https://www.hd.se",
  },
  {
    slug: "vasterbottens-kuriren",
    name: "Västerbottens-Kuriren",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Västerbotten",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Umeå",
    homepageUrl: "https://www.vk.se",
  },
  {
    slug: "upsala-nya-tidning",
    name: "Upsala Nya Tidning",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Uppsala",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Uppsala",
    homepageUrl: "https://www.unt.se",
  },
  {
    slug: "nerikes-allehanda",
    name: "Nerikes Allehanda",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Örebro",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Örebro",
    homepageUrl: "https://www.na.se",
  },
  {
    slug: "ostgota-correspondenten",
    name: "Östgöta Correspondenten",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Östergötland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Linköping",
    homepageUrl: "https://www.corren.se",
  },
  {
    slug: "boras-tidning",
    name: "Borås Tidning",
    tier: 2,
    type: "regional_daily",
    country: "SE",
    region: "Västra Götaland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Borås",
    homepageUrl: "https://www.bt.se",
  },
  {
    slug: "altinget-se",
    name: "Altinget.se",
    tier: 2,
    type: "trade_specialist",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    homepageUrl: "https://www.altinget.se",
  },
  {
    slug: "dagens-samhalle",
    name: "Dagens Samhälle",
    tier: 2,
    type: "trade_specialist",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    homepageUrl: "https://www.dagenssamhalle.se",
  },
  {
    slug: "riksdag-departement",
    name: "Riksdag & Departement",
    tier: 2,
    type: "trade_specialist",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    homepageUrl: "https://www.LRD.se",
  },
  {
    slug: "aktuell-hallbarhet",
    name: "Aktuell Hållbarhet",
    tier: 2,
    type: "trade_specialist",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    homepageUrl: "https://www.aktuellhallbarhet.se",
  },
  {
    slug: "lag-avtal",
    name: "Lag & Avtal",
    tier: 2,
    type: "trade_specialist",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    homepageUrl: "https://www.lag-avtal.se",
  },
  // Tier 3 — local papers
  {
    slug: "norrkopings-tidningar",
    name: "Norrköpings Tidningar",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Östergötland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Norrköping",
    homepageUrl: "https://www.nt.se",
  },
  {
    slug: "barometern",
    name: "Barometern",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Kalmar",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Kalmar",
    homepageUrl: "https://www.barometern.se",
  },
  {
    slug: "gotlands-tidningar",
    name: "Gotlands Tidningar",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Gotland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Visby",
    homepageUrl: "https://www.helagotland.se",
  },
  {
    slug: "hallands-nyheter",
    name: "Hallands Nyheter",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Halland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Falkenberg",
    homepageUrl: "https://www.hn.se",
  },
  {
    slug: "katrineholms-kuriren",
    name: "Katrineholms-Kuriren",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Södermanland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Katrineholm",
    homepageUrl: "https://www.kkuriren.se",
  },
  {
    slug: "norran",
    name: "Norran",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Västerbotten",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Skellefteå",
    homepageUrl: "https://www.norran.se",
  },
  {
    slug: "pitea-tidningen",
    name: "Piteå-Tidningen",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Norrbotten",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Piteå",
    homepageUrl: "https://www.pitea-tidningen.se",
  },
  {
    slug: "skaraborgs-allehanda",
    name: "Skaraborgs Allehanda",
    tier: 3,
    type: "local_paper",
    country: "SE",
    region: "Västra Götaland",
    language: "sv",
    isMajor: false,
    isPublicService: false,
    municipality: "Skövde",
    homepageUrl: "https://www.sla.se",
  },
  // Institutional sources
  {
    slug: "polisen-events",
    name: "Polisen",
    tier: 2,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    feedUrl: "https://polisen.se/aktuellt/rss/hela-landet/handelser-i-hela-landet/",
    homepageUrl: "https://polisen.se",
  },
  {
    slug: "smhi-warnings",
    name: "SMHI",
    tier: 2,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    feedUrl: "https://opendata-download-warnings.smhi.se/ibww/api/version/1/warning.json",
    homepageUrl: "https://www.smhi.se",
  },
  {
    slug: "riksdagen-open-data",
    name: "Riksdagen",
    tier: 2,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    feedUrl: "https://data.riksdagen.se/dokumentlista/?doktyp=mot&sort=datum&sortorder=desc&utformat=json",
    homepageUrl: "https://www.riksdagen.se",
  },
  {
    slug: "regeringen-rss",
    name: "Regeringen",
    tier: 2,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    feedUrl: "https://www.regeringen.se/rss/nyheter/",
    homepageUrl: "https://www.regeringen.se",
  },
  {
    slug: "domstol-se",
    name: "Sveriges Domstolar",
    tier: 3,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    homepageUrl: "https://www.domstol.se",
  },
  {
    slug: "jo",
    name: "Justitieombudsmannen",
    tier: 3,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    homepageUrl: "https://www.jo.se",
  },
  {
    slug: "imy",
    name: "IMY",
    tier: 3,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    homepageUrl: "https://www.imy.se",
  },
  {
    slug: "trafikverket",
    name: "Trafikverket",
    tier: 3,
    type: "institutional",
    country: "SE",
    region: "National",
    language: "sv",
    isMajor: false,
    isPublicService: true,
    homepageUrl: "https://www.trafikverket.se",
  },
];

// ─── International sources (mirror existing feeds.ts, enriched) ──────────────

const INTERNATIONAL_SOURCES: SourceMeta[] = [
  { slug: "bbc-world", name: "BBC World", tier: 1, type: "public_service", country: "GB", region: "Europe", language: "en", isMajor: true, isPublicService: true, feedUrl: "https://feeds.bbci.co.uk/news/world/rss.xml", homepageUrl: "https://www.bbc.com/news/world" },
  { slug: "al-jazeera", name: "Al Jazeera", tier: 1, type: "public_service", country: "QA", region: "Middle East", language: "en", isMajor: true, isPublicService: false, feedUrl: "https://www.aljazeera.com/xml/rss/all.xml", homepageUrl: "https://www.aljazeera.com" },
  { slug: "guardian-world", name: "The Guardian World", tier: 1, type: "national_daily", country: "GB", region: "Europe", language: "en", isMajor: true, isPublicService: false, feedUrl: "https://www.theguardian.com/world/rss", homepageUrl: "https://www.theguardian.com/world" },
  { slug: "dw-world", name: "DW", tier: 1, type: "public_service", country: "DE", region: "Europe", language: "en", isMajor: true, isPublicService: true, feedUrl: "https://rss.dw.com/rdf/rss-en-all", homepageUrl: "https://www.dw.com/en/top-stories/s-9097" },
  { slug: "france24", name: "France 24", tier: 1, type: "public_service", country: "FR", region: "Europe", language: "en", isMajor: true, isPublicService: true, feedUrl: "https://www.france24.com/en/rss", homepageUrl: "https://www.france24.com/en/" },
  { slug: "npr-world", name: "NPR World", tier: 1, type: "public_service", country: "US", region: "North America", language: "en", isMajor: true, isPublicService: true, feedUrl: "https://feeds.npr.org/1004/rss.xml", homepageUrl: "https://www.npr.org/sections/world/" },
  { slug: "pbs-newshour", name: "PBS NewsHour", tier: 1, type: "public_service", country: "US", region: "North America", language: "en", isMajor: true, isPublicService: true, feedUrl: "https://www.pbs.org/newshour/feeds/rss/headlines", homepageUrl: "https://www.pbs.org/newshour/world" },
  { slug: "cbs-world", name: "CBS World", tier: 1, type: "national_daily", country: "US", region: "North America", language: "en", isMajor: true, isPublicService: false, feedUrl: "https://www.cbsnews.com/latest/rss/world", homepageUrl: "https://www.cbsnews.com/world/" },
  { slug: "cnn-world", name: "CNN World", tier: 1, type: "national_daily", country: "US", region: "North America", language: "en", isMajor: true, isPublicService: false, feedUrl: "https://rss.cnn.com/rss/edition_world.rss", homepageUrl: "https://edition.cnn.com/world" },
  { slug: "cbc-world", name: "CBC World", tier: 2, type: "public_service", country: "CA", region: "North America", language: "en", isMajor: false, isPublicService: true, feedUrl: "https://www.cbc.ca/webfeed/rss/rss-world", homepageUrl: "https://www.cbc.ca/news/world" },
  { slug: "straits-times-world", name: "The Straits Times World", tier: 2, type: "national_daily", country: "SG", region: "Asia", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://www.straitstimes.com/news/world/rss.xml", homepageUrl: "https://www.straitstimes.com/world" },
  { slug: "the-hindu-international", name: "The Hindu International", tier: 2, type: "national_daily", country: "IN", region: "Asia", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://www.thehindu.com/news/international/feeder/default.rss", homepageUrl: "https://www.thehindu.com/news/international/" },
  { slug: "dawn-home", name: "Dawn", tier: 2, type: "national_daily", country: "PK", region: "Asia", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://www.dawn.com/feeds/home", homepageUrl: "https://www.dawn.com/world" },
  { slug: "jerusalem-post-world", name: "The Jerusalem Post", tier: 2, type: "national_daily", country: "IL", region: "Middle East", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://www.jpost.com/Rss/RssFeedsWorldNews", homepageUrl: "https://www.jpost.com/international" },
  { slug: "japan-times-world", name: "The Japan Times", tier: 2, type: "national_daily", country: "JP", region: "Asia", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://www.japantimes.co.jp/news_category/world/feed/", homepageUrl: "https://www.japantimes.co.jp/news/world/" },
  { slug: "times-of-india-world", name: "Times of India World", tier: 2, type: "national_daily", country: "IN", region: "Asia", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms", homepageUrl: "https://timesofindia.indiatimes.com/world" },
  { slug: "kyiv-independent", name: "The Kyiv Independent", tier: 2, type: "national_daily", country: "UA", region: "Europe", language: "en", isMajor: false, isPublicService: false, feedUrl: "https://kyivindependent.com/feed/", homepageUrl: "https://kyivindependent.com" },
];

export const ALL_SOURCES: SourceMeta[] = [...SWEDISH_SOURCES, ...INTERNATIONAL_SOURCES];

export const SOURCE_META_MAP = new Map(ALL_SOURCES.map((s) => [s.slug, s]));

export function getSourceMeta(slug: string): SourceMeta | undefined {
  return SOURCE_META_MAP.get(slug);
}

/** Swedish tier-1 slugs for use in scoring gates */
export const SWEDISH_TIER1_SLUGS = new Set(
  SWEDISH_SOURCES.filter((s) => s.tier === 1).map((s) => s.slug),
);

/** All Swedish source slugs */
export const SWEDISH_SOURCE_SLUGS = new Set(
  SWEDISH_SOURCES.map((s) => s.slug),
);

/** Institutional source slugs */
export const INSTITUTIONAL_SOURCE_SLUGS = new Set(
  ALL_SOURCES.filter((s) => s.type === "institutional").map((s) => s.slug),
);
